const wireDetailsReducer = (state = {wireDetailsObj:{
    wireID: null,
    senderInfoFormatVer: "",
    senderInfoUserReqCorrelation: "",
    senderInfoTestProdCode: "",
    senderInfoDupCode:"",
    typeCode:"",
    subtypeCode:"",
    inputCycleDate:"",
    inputSource: "",
    inputSeqNum: "",
    amount: "",
    senderABANum: "",
    senderShortName : "",
    receiverABANum : "",
    receiverShortName : "",
    businessFunctionCode : "",
    transactionTypeCode : "",
    senderReference : "",
    prevMsgID : "",
    localInstrumentCode : "",
    proprietaryCode : "",
    paymentNotificationIndicator : "",
    paymentContactEAddress : "",
    paymentContactName : "",
    paymentContactPhone : "",
    paymentContactMobile : "",
    paymentContactFax : "",
    paymentEndToEndID : "",
    detailsOfCharges : "",
    sendersChargesCurrency1 : "",
    sendersChargesAmount1 : "",
    sendersChargesCurrency2 : "",
    sendersChargesAmount2 : "",
    sendersChargesCurrency3 : "",
    sendersChargesAmount3 : "",
    sendersChargesCurrency4 : "",
    sendersChargesAmount4 : "",
    instructedAmountCurrencyCode : "",
    instructedAmount : "",
    exchangeRate : "",
    intermediaryFICode : "",
    intermediaryFIIdentifier : "",
    intermediaryFIName : "",
    intermediaryFIAddress1 : "",
    intermediaryFIAddress2 : "",
    intermediaryFIAddress3 : "",
    beneficiaryFICode : "",
    beneficiaryFIIdentifier : "",
    beneficiaryFIName : "",
    beneficiaryFIAddress1 : "",
    beneficiaryFIAddress2 : "",
    beneficiaryFIAddress3 : "",
    beneficiaryCode : "",
    beneficiaryIdentifier : "",
    beneficiaryName : "",
    beneficiaryAddress1 : "",
    beneficiaryAddress2 : "",
    beneficiaryAddress3 : "",
    referenceForBeneficiary : "",
    accountDebitedCode : "",
    accountDebitedIdentifier : "",
    accountDebitedName : "",
    accountDebitedAddress1 : "",
    accountDebitedAddress2 : "",
    accountDebitedAddress3 : "",
    originatorCode : "",
    originatorIdentifier : "",
    originatorName : "",
    originatorAddress1 : "",
    originatorAddress2 : "",
    originatorAddress3 : "",
    partyIDUniqeIDType : "",
    partyID : "",
    partyName : "",
    partyLineTag1 : "",
    partyLine1 : "",
    partyLineTag2 : "",
    partyLine2 : "",
    partyLineTag3 : "",
    partyLine3 : "",
    originatorFICode : "",
    originatorFIIdentifier : "",
    originatorFIName : "",
    originatorFIAddress1 : "",
    originatorFIAddress2 : "",
    originatorFIAddress3 : "",
    instructingFICode : "",
    instructingFIIdentifier : "",
    instructingFIName : "",
    instructingFIAddress1 : "",
    instructingFIAddress2 : "",
    instructingFIAddress3 : "",
    accountCreditedDrawdown : "",
    originToBeneficiaryInfo1 : "",
    originToBeneficiaryInfo2 : "",
    originToBeneficiaryInfo3 : "",
    originToBeneficiaryInfo4 : "",
    receiverFIInfo1 : "",
    receiverFIInfo2 : "",
    receiverFIInfo3 : "",
    receiverFIInfo4 : "",
    receiverFIInfo5 : "",
    receiverFIInfo6 : "",
    drawdownDebitAcctCode : "",
    drawdownDebitInfo1 : "",
    drawdownDebitInfo2 : "",
    drawdownDebitInfo3 : "",
    drawdownDebitInfo4 : "",
    drawdownDebitInfo5 : "",
    drawdownDebitInfo6 : "",
    intermediaryFIInfo1 : "",
    intermediaryFIInfo2 : "",
    intermediaryFIInfo3 : "",
    intermediaryFIInfo4 : "",
    intermediaryFIInfo5 : "",
    intermediaryFIInfo6 : "",
    intermediaryFIAdviceCode : "",
    intermediaryFIAdviceInfo1 : "",
    intermediaryFIAdviceInfo2 : "",
    intermediaryFIAdviceInfo3 : "",
    intermediaryFIAdviceInfo4 : "",
    intermediaryFIAdviceInfo5 : "",
    intermediaryFIAdviceInfo6 : "",
    beneficiaryFIInfo1 : "",
    beneficiaryFIInfo2 : "",
    beneficiaryFIInfo3 : "",
    beneficiaryFIInfo4 : "",
    beneficiaryFIInfo5 : "",
    beneficiaryFIInfo6 : "",
    beneficiaryFIAdviceCode: "",
    beneficiaryFIAdviceInfo1: "",
    beneficiaryFIAdviceInfo2: "",
    beneficiaryFIAdviceInfo3: "",
    beneficiaryFIAdviceInfo4: "",
    beneficiaryFIAdviceInfo5: "",
    beneficiaryFIAdviceInfo6: "",
    beneficiaryInfo1 : "",
    beneficiaryInfo2 : "",
    beneficiaryInfo3 : "",
    beneficiaryInfo4 : "",
    beneficiaryInfo5 : "",
    beneficiaryInfo6 : "",
    beneficiaryAdviceCode: "",
    beneficiaryAdviceInfo1: "",
    beneficiaryAdviceInfo2: "",
    beneficiaryAdviceInfo3: "",
    beneficiaryAdviceInfo4: "",
    beneficiaryAdviceInfo5: "",
    beneficiaryAdviceInfo6: "",
    methodOfPayment : "",
    methodOfPaymentInfo : "",
    FIToFIInfo1: "",
    FIToFIInfo2: "",
    FIToFIInfo3: "",
    FIToFIInfo4: "",
    FIToFIInfo5: "",
    FIToFIInfo6: "",
    seqBCurrencyInstructedAmountTag: "",
    seqBCurrencyInstructedAmount: "",
    seqBOrderingCustomerTag: "",
    seqBOrderingCustomerLine1: "",
    seqBOrderingCustomerLine2: "",
    seqBOrderingCustomerLine3: "",
    seqBOrderingCustomerLine4: "",
    seqBOrderingCustomerLine5: "",
    seqBOrderingInstitutionTag: "",
    seqBOrderingInstitutionLine1: "",
    seqBOrderingInstitutionLine2: "",
    seqBOrderingInstitutionLine3: "",
    seqBOrderingInstitutionLine4: "",
    seqBOrderingInstitutionLine5: "",
    seqBIntermediaryInstitutionTag: "",
    seqBIntermediaryInstitutionLine1: "",
    seqBIntermediaryInstitutionLine2: "",
    seqBIntermediaryInstitutionLine3: "",
    seqBIntermediaryInstitutionLine4: "",
    seqBIntermediaryInstitutionLine5: "",
    seqBAcctWithInstitutionTag: "",
    seqBAcctWithInstitutionLine1: "",
    seqBAcctWithInstitutionLine2: "",
    seqBAcctWithInstitutionLine3: "",
    seqBAcctWithInstitutionLine4: "",
    seqBAcctWithInstitutionLine5: "",
    seqBBeneficiaryCustomerTag: "",
    seqBBeneficiaryCustomerLine1: "",
    seqBBeneficiaryCustomerLine2: "",
    seqBBeneficiaryCustomerLine3: "",
    seqBBeneficiaryCustomerLine4: "",
    seqBBeneficiaryCustomerLine5: "",
    seqBRemittanceInfoTag: "",
    seqBRemittanceInfoLine1: "",
    seqBRemittanceInfoLine2: "",
    seqBRemittanceInfoLine3: "",
    seqBRemittanceInfoLine4: "",
    seqBRemittanceInfoLine5: "",
    seqBSenderToRecieverInfoTag: "",
    seqBSenderToRecieverInfoLine1: "",
    seqBSenderToRecieverInfoLine2: "",
    seqBSenderToRecieverInfoLine3: "",
    seqBSenderToRecieverInfoLine4: "",
    seqBSenderToRecieverInfoLine5: "",
    seqBSenderToRecieverInfoLine6: "",
    unstructuredAddendaLength: "",
    unstructuredAddendaInfo: "",
    relatedRemittanceID: "",
    relatedRemittanceMethod: "",
    relatedRemittanceEAddress: "",
    relatedRemittanceName: "",
    relatedRemittanceAddressType: "",
    relatedRemittanceDept: "",
    relatedRemittanceSubDept: "",
    relatedRemittanceStreetName: "",
    relatedRemittanceBuildingNum: "",
    relatedRemittancePostcode: "",
    relatedRemittanceTown: "",
    relatedRemittanceState: "",
    relatedRemittanceCountry: "",
    relatedRemittanceAddress1: "",
    relatedRemittanceAddress2: "",
    relatedRemittanceAddress3: "",
    relatedRemittanceAddress4: "",
    relatedRemittanceAddress5: "",
    relatedRemittanceAddress6: "",
    relatedRemittanceAddress7: "",
    serviceMessageInfoLine1: "",
    serviceMessageInfoLine2: "",
    serviceMessageInfoLine3: "",
    serviceMessageInfoLine4: "",
    serviceMessageInfoLine5: "",
    serviceMessageInfoLine6: "",
    serviceMessageInfoLine7: "",
    serviceMessageInfoLine8: "",
    serviceMessageInfoLine9: "",
    serviceMessageInfoLine10: "",
    serviceMessageInfoLine11: "",
    serviceMessageInfoLine12: "",
    messageDispositionFormatVer: "",
    messageDispositionTestProdCode: "",
    messageDispositionDupCode: "",
    messageDispositionStatus: "",
    receiptDate: "",
    receiptTime: "",
    receiptAppID: "",
    outputCycleDate: "",
    outputDestination: "",
    outputSeqNum: "",
    outputDate: "",
    outputTime: "",
    outputAppID: "",
    errorCategory: "",
    errorCode: "",
    errorDescription: "",
    errorMsg:"",
    textWireMsg:"",
    wireRemittance_by_wireID:[]
  }, wireRemittanceList:[]
}, action) => {
    switch(action.type){
        case "SETWIREDETAILS":
            return {
                ...state,
                wireDetailsObj: action.payload //[].concat(action.payload)//[...state.wires,action.payload],
            };
        case "SETWIREREMITTANCEDETAILS":
            return {
                ...state,
                wireRemittanceList: [].concat(action.payload)//[...state.wires,action.payload],
            };
        default:
        return state;
    }
}

export default wireDetailsReducer;