import React from "react";
import "./WireDetailForm.css";

function CustDateInput(props) {
  return (
    <div className="form-group row">
      <label className="col-sm-3 col-form-label">{props.labelText}</label>
      <div className="col-sm-9">
        <input
          type="date"
          name={props.nameref}
          className="form-control"
          placeholder={props.placeholdertext}
          value={props.val}
          onChange={e => props.inputchange(e)}
          readOnly={props.readOnlyVal}
        />
      </div>
    </div>
  );
}

function CustTextInput(props) {
  return (
    <div className="form-group row">
      <label className="col-sm-5 col-form-label">{props.labelText}</label>
      <div className="col-sm-7">
        <input
          type="text"
          name={props.nameref}
          className="form-control"
          //placeholder={props.placeholdertext}
          value={props.val}
          onChange={e => props.inputchange(e)}
          readOnly={props.readOnlyVal}
        />
      </div>
    </div>
  );
}

function CustCheckBoxInput(props) {
  return (
    <div className="form-group row">
      <label className="col-sm-3 col-form-label">{props.labelText}</label>
      <div className="col-sm-9">
        <div className="form-check text-left">
          <input
            type="checkbox"
            name={props.nameref}
            className="form-check-input"
            placeholder={props.placeholdertext}
            //value={props.val}
            checked={props.checkedVal}
            onChange={e => props.inputchange(e)}
            disabled={props.disableVal}
          />
        </div>
      </div>
    </div>
  );
}

function WireDetailForm(props) {
  return (
    <React.Fragment>
      <div className="sm-vert-form form-row">
        <div className="col-sm-4 mb-3">
          <CustTextInput
            placeholdertext="senderInfoFormatVer"
            labelText="senderInfoFormatVer"
            nameref="senderInfoFormatVer"
            inputchange={props.oncustinputchange}
            val={props.custstate.senderInfoFormatVer}
          />
          <CustTextInput
            placeholdertext="senderInfoDupCode"
            labelText="senderInfoDupCode"
            nameref="senderInfoDupCode"
            inputchange={props.oncustinputchange}
            val={props.custstate.senderInfoDupCode}
          />
          <CustTextInput
            placeholdertext="inputCycleDate"
            labelText="inputCycleDate"
            nameref="inputCycleDate"
            inputchange={props.oncustinputchange}
            val={props.custstate.inputCycleDate}
          />
           
          <CustTextInput
            placeholdertext="amount"
            labelText="amount"
            nameref="amount"
            inputchange={props.oncustinputchange}
            val={props.custstate.amount}
          />
          <CustTextInput
            placeholdertext="receiverABANum"
            labelText="receiverABANum"
            nameref="receiverABANum"
            inputchange={props.oncustinputchange}
            val={props.custstate.receiverABANum}
          />
           <CustTextInput
            placeholdertext="transactionTypeCode"
            labelText="transactionTypeCode"
            nameref="transactionTypeCode"
            inputchange={props.oncustinputchange}
            val={props.custstate.transactionTypeCode}
          />
          
          <CustTextInput
            placeholdertext="localInstrumentCode"
            labelText="localInstrumentCode"
            nameref="localInstrumentCode"
            inputchange={props.oncustinputchange}
            val={props.custstate.localInstrumentCode}
          />
          <CustTextInput
            placeholdertext="paymentContactEAddress"
            labelText="paymentContactEAddress"
            nameref="paymentContactEAddress"
            inputchange={props.oncustinputchange}
            val={props.custstate.paymentContactEAddress}
          />
          <CustTextInput
            placeholdertext="paymentContactMobile"
            labelText="paymentContactMobile"
            nameref="paymentContactMobile"
            inputchange={props.oncustinputchange}
            val={props.custstate.paymentContactMobile}
          />
          <CustTextInput
            placeholdertext="detailsOfCharges"
            labelText="DetailsOfCharges"
            nameref="detailsOfCharges"
            inputchange={props.oncustinputchange}
            val={props.custstate.detailsOfCharges}
          />
          <CustTextInput
            placeholdertext="sendersChargesCurrency2"
            labelText="SendersChargesCurrency2"
            nameref="sendersChargesCurrency2"
            inputchange={props.oncustinputchange}
            val={props.custstate.sendersChargesCurrency2}
          />
          <CustTextInput
            placeholdertext="sendersChargesAmount3"
            labelText="SendersChargesAmount3"
            nameref="sendersChargesAmount3"
            inputchange={props.oncustinputchange}
            val={props.custstate.sendersChargesAmount3}
          />
          <CustTextInput
            placeholdertext="instructedAmountCurrencyCode"
            labelText="instructedAmountCurrencyCode"
            nameref="instructedAmountCurrencyCode"
            inputchange={props.oncustinputchange}
            val={props.custstate.instructedAmountCurrencyCode}
          />
          <CustTextInput
            placeholdertext="intermediaryFICode"
            labelText="intermediaryFICode"
            nameref="intermediaryFICode"
            inputchange={props.oncustinputchange}
            val={props.custstate.intermediaryFICode}
          />
          <CustTextInput
            placeholdertext="intermediaryFIAddress1"
            labelText="intermediaryFIAddress1"
            nameref="intermediaryFIAddress1"
            inputchange={props.oncustinputchange}
            val={props.custstate.intermediaryFIAddress1}
          />
          <CustTextInput
            placeholdertext="beneficiaryFICode"
            labelText="beneficiaryFICode"
            nameref="beneficiaryFICode"
            inputchange={props.oncustinputchange}
            val={props.custstate.beneficiaryFICode}
          />
          <CustTextInput
            placeholdertext="beneficiaryFIAddress1"
            labelText="beneficiaryFIAddress1"
            nameref="beneficiaryFIAddress1"
            inputchange={props.oncustinputchange}
            val={props.custstate.beneficiaryFIAddress1}
          />
          <CustTextInput
            placeholdertext="beneficiaryCode"
            labelText="beneficiaryCode"
            nameref="beneficiaryCode"
            inputchange={props.oncustinputchange}
            val={props.custstate.beneficiaryCode}
          />
          <CustTextInput
            placeholdertext="beneficiaryAddress1"
            labelText="beneficiaryAddress1"
            nameref="beneficiaryAddress1"
            inputchange={props.oncustinputchange}
            val={props.custstate.beneficiaryAddress1}
          />
          <CustTextInput
            placeholdertext="referenceForBeneficiary"
            labelText="referenceForBeneficiary"
            nameref="referenceForBeneficiary"
            inputchange={props.oncustinputchange}
            val={props.custstate.referenceForBeneficiary}
          />
          <CustTextInput
            placeholdertext="accountDebitedName"
            labelText="accountDebitedName"
            nameref="accountDebitedName"
            inputchange={props.oncustinputchange}
            val={props.custstate.accountDebitedName}
          />
          <CustTextInput
            placeholdertext="accountDebitedAddress3"
            labelText="accountDebitedAddress3"
            nameref="accountDebitedAddress3"
            inputchange={props.oncustinputchange}
            val={props.custstate.accountDebitedAddress3}
          />
          <CustTextInput
            placeholdertext="originatorName"
            labelText="originatorName"
            nameref="originatorName"
            inputchange={props.oncustinputchange}
            val={props.custstate.originatorName}
          />
          <CustTextInput
            placeholdertext="originatorAddress3"
            labelText="originatorAddress3"
            nameref="originatorAddress3"
            inputchange={props.oncustinputchange}
            val={props.custstate.originatorAddress3}
          />
          <CustTextInput
            placeholdertext="partyName"
            labelText="partyName"
            nameref="partyName"
            inputchange={props.oncustinputchange}
            val={props.custstate.partyName}
          />
          <CustTextInput
            placeholdertext="partyLineTag2"
            labelText="partyLineTag2"
            nameref="partyLineTag2"
            inputchange={props.oncustinputchange}
            val={props.custstate.partyLineTag2}
          />
          <CustTextInput
            placeholdertext="partyLine3"
            labelText="partyLine3"
            nameref="partyLine3"
            inputchange={props.oncustinputchange}
            val={props.custstate.partyLine3}
          />
          <CustTextInput
            placeholdertext="originatorFIName"
            labelText="originatorFIName"
            nameref="originatorFIName"
            inputchange={props.oncustinputchange}
            val={props.custstate.originatorFIName}
          />
          <CustTextInput
            placeholdertext="originatorFIAddress3"
            labelText="originatorFIAddress3"
            nameref="originatorFIAddress3"
            inputchange={props.oncustinputchange}
            val={props.custstate.originatorFIAddress3}
          />
          <CustTextInput
            placeholdertext="instructingFIName"
            labelText="instructingFIName"
            nameref="instructingFIName"
            inputchange={props.oncustinputchange}
            val={props.custstate.instructingFIName}
          />
          <CustTextInput
            placeholdertext="instructingFIAddress3"
            labelText="instructingFIAddress3"
            nameref="instructingFIAddress3"
            inputchange={props.oncustinputchange}
            val={props.custstate.instructingFIAddress3}
          />
          <CustTextInput
            placeholdertext="originToBeneficiaryInfo2"
            labelText="originToBeneficiaryInfo2"
            nameref="originToBeneficiaryInfo2"
            inputchange={props.oncustinputchange}
            val={props.custstate.originToBeneficiaryInfo2}
          />
          <CustTextInput
            placeholdertext="receiverFIInfo1"
            labelText="receiverFIInfo1"
            nameref="receiverFIInfo1"
            inputchange={props.oncustinputchange}
            val={props.custstate.receiverFIInfo1}
          />
          <CustTextInput
            placeholdertext="receiverFIInfo4"
            labelText="receiverFIInfo4"
            nameref="receiverFIInfo4"
            inputchange={props.oncustinputchange}
            val={props.custstate.receiverFIInfo4}
          />
           <CustTextInput
            placeholdertext="drawdownDebitAcctCode"
            labelText="drawdownDebitAcctCode"
            nameref="drawdownDebitAcctCode"
            inputchange={props.oncustinputchange}
            val={props.custstate.drawdownDebitAcctCode}
          />
          <CustTextInput
            placeholdertext="drawdownDebitInfo3"
            labelText="drawdownDebitInfo3"
            nameref="drawdownDebitInfo3"
            inputchange={props.oncustinputchange}
            val={props.custstate.drawdownDebitInfo3}
          />
          <CustTextInput
            placeholdertext="drawdownDebitInfo6"
            labelText="drawdownDebitInfo6"
            nameref="drawdownDebitInfo6"
            inputchange={props.oncustinputchange}
            val={props.custstate.drawdownDebitInfo6}
          />
        </div>

        <div className="col-sm-4 mb-3">
        <CustTextInput
            placeholdertext="senderInfoUserReqCorrelation"
            labelText="senderInfoUserReqCorrelation"
            nameref="senderInfoUserReqCorrelation"
            inputchange={props.oncustinputchange}
            val={props.custstate.senderInfoUserReqCorrelation}
          />
          <CustTextInput
            placeholdertext="typeCode"
            labelText="typeCode"
            nameref="typeCode"
            inputchange={props.oncustinputchange}
            val={props.custstate.typeCode}
          />
          <CustTextInput
            placeholdertext="inputSource"
            labelText="inputSource"
            nameref="inputSource"
            inputchange={props.oncustinputchange}
            val={props.custstate.inputSource}
          />
          <CustTextInput
            placeholdertext="senderABANum"
            labelText="senderABANum"
            nameref="senderABANum"
            inputchange={props.oncustinputchange}
            val={props.custstate.senderABANum}
          />
          <CustTextInput
            placeholdertext="receiverShortName"
            labelText="receiverShortName"
            nameref="receiverShortName"
            inputchange={props.oncustinputchange}
            val={props.custstate.receiverShortName}
          />
          <CustTextInput
            placeholdertext="senderReference"
            labelText="senderReference"
            nameref="senderReference"
            inputchange={props.oncustinputchange}
            val={props.custstate.senderReference}
          />
          <CustTextInput
            placeholdertext="proprietaryCode"
            labelText="proprietaryCode"
            nameref="proprietaryCode"
            inputchange={props.oncustinputchange}
            val={props.custstate.proprietaryCode}
          />
          
          <CustTextInput
            placeholdertext="paymentContactName"
            labelText="paymentContactName"
            nameref="paymentContactName"
            inputchange={props.oncustinputchange}
            val={props.custstate.paymentContactName}
          />
          <CustTextInput
            placeholdertext="paymentContactFax"
            labelText="paymentContactFax"
            nameref="paymentContactFax"
            inputchange={props.oncustinputchange}
            val={props.custstate.paymentContactFax}
          />
          <CustTextInput
            placeholdertext="sendersChargesCurrency1"
            labelText="SendersChargesCurrency1"
            nameref="sendersChargesCurrency1"
            inputchange={props.oncustinputchange}
            val={props.custstate.sendersChargesCurrency1}
          />
          <CustTextInput
            placeholdertext="sendersChargesAmount2"
            labelText="sendersChargesAmount2"
            nameref="sendersChargesAmount2"
            inputchange={props.oncustinputchange}
            val={props.custstate.sendersChargesAmount2}
          />
          <CustTextInput
            placeholdertext="sendersChargesCurrency4"
            labelText="SendersChargesCurrency4"
            nameref="sendersChargesCurrency4"
            inputchange={props.oncustinputchange}
            val={props.custstate.sendersChargesCurrency4}
          />
          <CustTextInput
            placeholdertext="instructedAmount"
            labelText="instructedAmount"
            nameref="instructedAmount"
            inputchange={props.oncustinputchange}
            val={props.custstate.instructedAmount}
          />
          <CustTextInput
            placeholdertext="intermediaryFIIdentifier"
            labelText="intermediaryFIIdentifier"
            nameref="intermediaryFIIdentifier"
            inputchange={props.oncustinputchange}
            val={props.custstate.intermediaryFIIdentifier}
          />
          <CustTextInput
            placeholdertext="intermediaryFIAddress2"
            labelText="intermediaryFIAddress2"
            nameref="intermediaryFIAddress2"
            inputchange={props.oncustinputchange}
            val={props.custstate.intermediaryFIAddress2}
          />
          <CustTextInput
            placeholdertext="beneficiaryFIIdentifier"
            labelText="beneficiaryFIIdentifier"
            nameref="beneficiaryFIIdentifier"
            inputchange={props.oncustinputchange}
            val={props.custstate.beneficiaryFIIdentifier}
          />
          <CustTextInput
            placeholdertext="beneficiaryFIAddress2"
            labelText="beneficiaryFIAddress2"
            nameref="beneficiaryFIAddress2"
            inputchange={props.oncustinputchange}
            val={props.custstate.beneficiaryFIAddress2}
          />
          <CustTextInput
            placeholdertext="beneficiaryIdentifier"
            labelText="beneficiaryIdentifier"
            nameref="beneficiaryIdentifier"
            inputchange={props.oncustinputchange}
            val={props.custstate.beneficiaryIdentifier}
          />
          <CustTextInput
            placeholdertext="beneficiaryAddress2"
            labelText="beneficiaryAddress2"
            nameref="beneficiaryAddress2"
            inputchange={props.oncustinputchange}
            val={props.custstate.beneficiaryAddress2}
          />
          <CustTextInput
            placeholdertext="accountDebitedCode"
            labelText="accountDebitedCode"
            nameref="accountDebitedCode"
            inputchange={props.oncustinputchange}
            val={props.custstate.accountDebitedCode}
          />
           <CustTextInput
            placeholdertext="accountDebitedAddress1"
            labelText="accountDebitedAddress1"
            nameref="accountDebitedAddress1"
            inputchange={props.oncustinputchange}
            val={props.custstate.accountDebitedAddress1}
          />
          <CustTextInput
            placeholdertext="originatorCode"
            labelText="originatorCode"
            nameref="originatorCode"
            inputchange={props.oncustinputchange}
            val={props.custstate.originatorCode}
          />
          <CustTextInput
            placeholdertext="originatorAddress1"
            labelText="originatorAddress1"
            nameref="originatorAddress1"
            inputchange={props.oncustinputchange}
            val={props.custstate.originatorAddress1}
          />
          <CustTextInput
            placeholdertext="partyIDUniqeIDType"
            labelText="partyIDUniqeIDType"
            nameref="partyIDUniqeIDType"
            inputchange={props.oncustinputchange}
            val={props.custstate.partyIDUniqeIDType}
          />
          <CustTextInput
            placeholdertext="partyLineTag1"
            labelText="partyLineTag1"
            nameref="partyLineTag1"
            inputchange={props.oncustinputchange}
            val={props.custstate.partyLineTag1}
          />
          <CustTextInput
            placeholdertext="partyLine2"
            labelText="partyLine2"
            nameref="partyLine2"
            inputchange={props.oncustinputchange}
            val={props.custstate.partyLine2}
          />
          <CustTextInput
            placeholdertext="originatorFICode"
            labelText="originatorFICode"
            nameref="originatorFICode"
            inputchange={props.oncustinputchange}
            val={props.custstate.originatorFICode}
          />
          <CustTextInput
            placeholdertext="originatorFIAddress1"
            labelText="originatorFIAddress1"
            nameref="originatorFIAddress1"
            inputchange={props.oncustinputchange}
            val={props.custstate.originatorFIAddress1}
          />
          <CustTextInput
            placeholdertext="instructingFICode"
            labelText="instructingFICode"
            nameref="instructingFICode"
            inputchange={props.oncustinputchange}
            val={props.custstate.instructingFICode}
          />
          <CustTextInput
            placeholdertext="instructingFIAddress1"
            labelText="instructingFIAddress1"
            nameref="instructingFIAddress1"
            inputchange={props.oncustinputchange}
            val={props.custstate.instructingFIAddress1}
          />
          <CustTextInput
            placeholdertext="accountCreditedDrawdown"
            labelText="accountCreditedDrawdown"
            nameref="accountCreditedDrawdown"
            inputchange={props.oncustinputchange}
            val={props.custstate.accountCreditedDrawdown}
          />
          <CustTextInput
            placeholdertext="originToBeneficiaryInfo3"
            labelText="originToBeneficiaryInfo3"
            nameref="originToBeneficiaryInfo3"
            inputchange={props.oncustinputchange}
            val={props.custstate.originToBeneficiaryInfo3}
          />
          <CustTextInput
            placeholdertext="receiverFIInfo2"
            labelText="receiverFIInfo2"
            nameref="receiverFIInfo2"
            inputchange={props.oncustinputchange}
            val={props.custstate.receiverFIInfo2}
          />
          <CustTextInput
            placeholdertext="receiverFIInfo5"
            labelText="receiverFIInfo5"
            nameref="receiverFIInfo5"
            inputchange={props.oncustinputchange}
            val={props.custstate.receiverFIInfo5}
          />
          <CustTextInput
            placeholdertext="drawdownDebitInfo1"
            labelText="drawdownDebitInfo1"
            nameref="drawdownDebitInfo1"
            inputchange={props.oncustinputchange}
            val={props.custstate.drawdownDebitInfo1}
          />
          <CustTextInput
            placeholdertext="drawdownDebitInfo4"
            labelText="drawdownDebitInfo4"
            nameref="drawdownDebitInfo4"
            inputchange={props.oncustinputchange}
            val={props.custstate.drawdownDebitInfo4}
          />
          <CustTextInput
            placeholdertext="intermediaryFIInfo1"
            labelText="intermediaryFIInfo1"
            nameref="intermediaryFIInfo1"
            inputchange={props.oncustinputchange}
            val={props.custstate.intermediaryFIInfo1}
          />
        </div>

        <div className="col-sm-4">
        <CustTextInput
            placeholdertext="senderInfoTestProdCode"
            labelText="senderInfoTestProdCode"
            nameref="senderInfoTestProdCode"
            inputchange={props.oncustinputchange}
            val={props.custstate.senderInfoTestProdCode}
          />
          <CustTextInput
            placeholdertext="subtypeCode"
            labelText="subtypeCode"
            nameref="subtypeCode"
            inputchange={props.oncustinputchange}
            val={props.custstate.subtypeCode}
          />
          <CustTextInput
            placeholdertext="inputSeqNum"
            labelText="inputSeqNum"
            nameref="inputSeqNum"
            inputchange={props.oncustinputchange}
            val={props.custstate.inputSeqNum}
          />
           <CustTextInput
            placeholdertext="senderShortName"
            labelText="senderShortName"
            nameref="senderShortName"
            inputchange={props.oncustinputchange}
            val={props.custstate.senderShortName}
          />
          <CustTextInput
            placeholdertext="businessFunctionCode"
            labelText="businessFunctionCode"
            nameref="businessFunctionCode"
            inputchange={props.oncustinputchange}
            val={props.custstate.businessFunctionCode}
          />
          <CustTextInput
            placeholdertext="prevMsgID"
            labelText="prevMsgID"
            nameref="prevMsgID"
            inputchange={props.oncustinputchange}
            val={props.custstate.prevMsgID}
          />
          <CustTextInput 
            labelText="paymentNotificationIndicator"
            nameref="paymentNotificationIndicator"
            inputchange={props.oncustinputchange}
            val={props.custstate.paymentNotificationIndicator}
          />
          <CustTextInput
            placeholdertext="paymentContactPhone"
            labelText="paymentContactPhone"
            nameref="paymentContactPhone"
            inputchange={props.oncustinputchange}
            val={props.custstate.paymentContactPhone}
          />
          <CustTextInput
            placeholdertext="paymentEndToEndID"
            labelText="paymentEndToEndID"
            nameref="paymentEndToEndID"
            inputchange={props.oncustinputchange}
            val={props.custstate.paymentEndToEndID}
          />
          <CustTextInput
            placeholdertext="sendersChargesAmount1"
            labelText="SendersChargesAmount1"
            nameref="sendersChargesAmount1"
            inputchange={props.oncustinputchange}
            val={props.custstate.sendersChargesAmount1}
          />
          <CustTextInput
            placeholdertext="sendersChargesCurrency3"
            labelText="sendersChargesCurrency3"
            nameref="sendersChargesCurrency3"
            inputchange={props.oncustinputchange}
            val={props.custstate.sendersChargesCurrency3}
          />
          <CustTextInput
            placeholdertext="sendersChargesAmount4"
            labelText="sendersChargesAmount4"
            nameref="sendersChargesAmount4"
            inputchange={props.oncustinputchange}
            val={props.custstate.sendersChargesAmount4}
          />
          <CustTextInput
            placeholdertext="exchangeRate"
            labelText="exchangeRate"
            nameref="exchangeRate"
            inputchange={props.oncustinputchange}
            val={props.custstate.exchangeRate}
          />
          <CustTextInput
            placeholdertext="intermediaryFIName"
            labelText="intermediaryFIName"
            nameref="intermediaryFIName"
            inputchange={props.oncustinputchange}
            val={props.custstate.intermediaryFIName}
          />
          <CustTextInput
            placeholdertext="intermediaryFIAddress3"
            labelText="intermediaryFIAddress3"
            nameref="intermediaryFIAddress3"
            inputchange={props.oncustinputchange}
            val={props.custstate.intermediaryFIAddress3}
          />
          <CustTextInput
            placeholdertext="beneficiaryFIName"
            labelText="beneficiaryFIName"
            nameref="beneficiaryFIName"
            inputchange={props.oncustinputchange}
            val={props.custstate.beneficiaryFIName}
          />
          <CustTextInput
            placeholdertext="beneficiaryFIAddress3"
            labelText="beneficiaryFIAddress3"
            nameref="beneficiaryFIAddress3"
            inputchange={props.oncustinputchange}
            val={props.custstate.beneficiaryFIAddress3}
          />
          <CustTextInput
            placeholdertext="beneficiaryName"
            labelText="beneficiaryName"
            nameref="beneficiaryName"
            inputchange={props.oncustinputchange}
            val={props.custstate.beneficiaryName}
          />
          <CustTextInput
            placeholdertext="beneficiaryAddress3"
            labelText="beneficiaryAddress3"
            nameref="beneficiaryAddress3"
            inputchange={props.oncustinputchange}
            val={props.custstate.beneficiaryAddress3}
          />
          <CustTextInput
            placeholdertext="accountDebitedIdentifier"
            labelText="accountDebitedIdentifier"
            nameref="accountDebitedIdentifier"
            inputchange={props.oncustinputchange}
            val={props.custstate.accountDebitedIdentifier}
          />
          <CustTextInput
            placeholdertext="accountDebitedAddress2"
            labelText="accountDebitedAddress2"
            nameref="accountDebitedAddress2"
            inputchange={props.oncustinputchange}
            val={props.custstate.accountDebitedAddress2}
          />
          <CustTextInput
            placeholdertext="originatorIdentifier"
            labelText="originatorIdentifier"
            nameref="originatorIdentifier"
            inputchange={props.oncustinputchange}
            val={props.custstate.originatorIdentifier}
          />
          <CustTextInput
            placeholdertext="originatorAddress2"
            labelText="originatorAddress2"
            nameref="originatorAddress2"
            inputchange={props.oncustinputchange}
            val={props.custstate.originatorAddress2}
          />
          <CustTextInput
            placeholdertext="partyID"
            labelText="partyID"
            nameref="partyID"
            inputchange={props.oncustinputchange}
            val={props.custstate.partyID}
          />
          <CustTextInput
            placeholdertext="partyLine1"
            labelText="partyLine1"
            nameref="partyLine1"
            inputchange={props.oncustinputchange}
            val={props.custstate.partyLine1}
          />
          <CustTextInput
            placeholdertext="partyLineTag3"
            labelText="partyLineTag3"
            nameref="partyLineTag3"
            inputchange={props.oncustinputchange}
            val={props.custstate.partyLineTag3}
          />
          <CustTextInput
            placeholdertext="originatorFIIdentifier"
            labelText="originatorFIIdentifier"
            nameref="originatorFIIdentifier"
            inputchange={props.oncustinputchange}
            val={props.custstate.originatorFIIdentifier}
          />
          <CustTextInput
            placeholdertext="originatorFIAddress2"
            labelText="originatorFIAddress2"
            nameref="originatorFIAddress2"
            inputchange={props.oncustinputchange}
            val={props.custstate.originatorFIAddress2}
          />
          <CustTextInput
            placeholdertext="instructingFIIdentifier"
            labelText="instructingFIIdentifier"
            nameref="instructingFIIdentifier"
            inputchange={props.oncustinputchange}
            val={props.custstate.instructingFIIdentifier}
          />
          <CustTextInput
            placeholdertext="instructingFIAddress2"
            labelText="instructingFIAddress2"
            nameref="instructingFIAddress2"
            inputchange={props.oncustinputchange}
            val={props.custstate.instructingFIAddress2}
          />
          <CustTextInput
            placeholdertext="originToBeneficiaryInfo1"
            labelText="originToBeneficiaryInfo1"
            nameref="originToBeneficiaryInfo1"
            inputchange={props.oncustinputchange}
            val={props.custstate.originToBeneficiaryInfo1}
          />
           <CustTextInput
            placeholdertext="originToBeneficiaryInfo4"
            labelText="originToBeneficiaryInfo4"
            nameref="originToBeneficiaryInfo4"
            inputchange={props.oncustinputchange}
            val={props.custstate.originToBeneficiaryInfo4}
          />
          <CustTextInput
            placeholdertext="receiverFIInfo3"
            labelText="receiverFIInfo3"
            nameref="receiverFIInfo3"
            inputchange={props.oncustinputchange}
            val={props.custstate.receiverFIInfo3}
          />
          <CustTextInput
            placeholdertext="receiverFIInfo6"
            labelText="receiverFIInfo6"
            nameref="receiverFIInfo6"
            inputchange={props.oncustinputchange}
            val={props.custstate.receiverFIInfo6}
          />
          <CustTextInput
            placeholdertext="drawdownDebitInfo2"
            labelText="drawdownDebitInfo2"
            nameref="drawdownDebitInfo2"
            inputchange={props.oncustinputchange}
            val={props.custstate.drawdownDebitInfo2}
          />
          <CustTextInput
            placeholdertext="drawdownDebitInfo5"
            labelText="drawdownDebitInfo5"
            nameref="drawdownDebitInfo5"
            inputchange={props.oncustinputchange}
            val={props.custstate.drawdownDebitInfo5}
          />
           <CustTextInput
            placeholdertext="intermediaryFIInfo2"
            labelText="intermediaryFIInfo2"
            nameref="intermediaryFIInfo2"
            inputchange={props.oncustinputchange}
            val={props.custstate.intermediaryFIInfo2}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

export default WireDetailForm;
